name: Pages Build and Deployment

on:
  push:
    branches:
      - main
    paths:
      - README.md
      - .github/workflows/**

  pull_request:
    branches:
      - main
    paths:
      - README.md
      - .github/workflows/**

jobs:
  dummy-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check README.md
        run: echo "✅ README.md trigger test passed"
